### PR TITLE
Missing @Nullable in AsyncMap, Context, Vertx and WorkerExecutor

### LINKED ISSUE #2434: Missing @Nullable annotations
Building this list so that we can track any missing `@Nullable` annotation until 3.6 is released

[ ] `Vertx.executeBlocking`

[ ] `Context.executeBlocking`

[ ] `WorkerExecutor.executeBlocking`

[ ] `AsyncMap.get`
[ ] `AsyncMap.putIfAbsent`
[ ] `AsyncMap.remove`
[ ] `AsyncMap.replace`

------ _Original comment_

Currently, the `executeBlocking` result handler type is not annotated with `@Nullable`.

As a result, the generated Rxified API returns a `Single<T>`. But it's quite common to use `Future<Void>` for a blocking task which does not need to return any result.
Then if the user simply invoke `future.complete()`, the program fails at runtime.

As a workaround, the user can use a `Future<Object>` and invoke `complete()` with any non-null value.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #2434

Improves Vert.x RxJava2 API (returns Maybe instead of Single)

With executeBlocking, the future provided to the blocking handler could be completed with null.

In AsyncMap, there are a few cases (get, remove, replace, putIfAbsent) when the result can be null as well.

### CODE REVIEW

File: src/main/java/io/vertx/core/Context.java [hunk 1]
```diff
@@ -116,15 +116,15 @@ static boolean isOnVertxThread() {
...
+  <T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, boolean ordered, Handler<AsyncResult<@Nullable T>> resultHandler);
 
   /**
    * Invoke {@link #executeBlocking(Handler, boolean, Handler)} with order = true.
    * @param blockingCodeHandler  handler representing the blocking code to run
    * @param resultHandler  handler that will be called when the blocking code is complete
    * @param <T> the type of the result
    */
-  <T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, Handler<AsyncResult<T>> resultHandler);
+  <T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, Handler<AsyncResult<@Nullable T>> resultHandler);
```
Comment (vietj) [inline src/main/java/io/vertx/core/Context.java]: it needs also to be `Handler<Future<@Nullable T>>`

File: src/main/java/io/vertx/core/Vertx.java [hunk 2]
```diff
@@ -519,12 +519,12 @@ static void clusteredVertx(VertxOptions options, Handler<AsyncResult<Vertx>> res
    *                 guarantees
    * @param <T> the type of the result
    */
-  <T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, boolean ordered, Handler<AsyncResult<T>> resultHandler);
+  <T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, boolean ordered, Handler<AsyncResult<@Nullable T>> resultHandler);
```
Comment (vietj) [inline src/main/java/io/vertx/core/Vertx.java]: it needs also to be `Handler<Future<@Nullable T>>`

File: src/main/java/io/vertx/core/Vertx.java [hunk 3]
```diff
@@ -519,12 +519,12 @@ static void clusteredVertx(VertxOptions options, Handler<AsyncResult<Vertx>> res
...
 
   /**
    * Like {@link #executeBlocking(Handler, boolean, Handler)} called with ordered = true.
    */
-  <T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, Handler<AsyncResult<T>> resultHandler);
+  <T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, Handler<AsyncResult<@Nullable T>> resultHandler);
```
Comment (vietj) [inline src/main/java/io/vertx/core/Vertx.java]: it needs also to be `Handler<Future<@Nullable T>>`

File: src/main/java/io/vertx/core/WorkerExecutor.java [hunk 4]
```diff
@@ -47,12 +48,12 @@
    *                 guarantees
    * @param <T> the type of the result
    */
-  <T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, boolean ordered, Handler<AsyncResult<T>> resultHandler);
+  <T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, boolean ordered, Handler<AsyncResult<@Nullable T>> resultHandler);
```
Comment (vietj) [inline src/main/java/io/vertx/core/WorkerExecutor.java]: it needs also to be `Handler<Future<@Nullable T>>`

File: src/main/java/io/vertx/core/WorkerExecutor.java [hunk 5]
```diff
@@ -47,12 +48,12 @@
...
 
   /**
    * Like {@link #executeBlocking(Handler, boolean, Handler)} called with ordered = true.
    */
-  default <T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, Handler<AsyncResult<T>> resultHandler) {
+  default <T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, Handler<AsyncResult<@Nullable T>> resultHandler) {
```
Comment (vietj) [inline src/main/java/io/vertx/core/WorkerExecutor.java]: it needs also to be `Handler<Future<@Nullable T>>`

File: src/main/java/io/vertx/core/shareddata/AsyncMap.java [hunk 6]
```diff
@@ -81,15 +82,15 @@
    * @param ttl  The time to live (in ms) for the entry
    * @param completionHandler  the handler
    */
-  void putIfAbsent(K k, V v, long ttl, Handler<AsyncResult<V>> completionHandler);
+  void putIfAbsent(K k, V v, long ttl, Handler<AsyncResult<@Nullable V>> completionHandler);
```
Comment (vietj) [inline src/main/java/io/vertx/core/shareddata/AsyncMap.java]: the second param `V` should also be `@Nullable`

File: src/main/java/io/vertx/core/shareddata/AsyncMap.java [hunk 7]
```diff
@@ -108,7 +109,7 @@
    * @param v  the new value
    * @param resultHandler  the result handler will be passed the previous value
    */
-  void replace(K k, V v, Handler<AsyncResult<V>> resultHandler);
+  void replace(K k, V v, Handler<AsyncResult<@Nullable V>> resultHandler);
```
Comment (vietj) [inline src/main/java/io/vertx/core/shareddata/AsyncMap.java]: the second param `V` should also be `@Nullable`

File: src/main/java/io/vertx/core/shareddata/AsyncMap.java (hunk 6 above)
Comment (tsegismont) [reply src/main/java/io/vertx/core/shareddata/AsyncMap.java]: No, null values are forbidden in `AsyncMap`.

File: src/main/java/io/vertx/core/shareddata/AsyncMap.java (hunk 7 above)
Comment (tsegismont) [reply src/main/java/io/vertx/core/shareddata/AsyncMap.java]: No, null values are forbidden in AsyncMap.

**Comment by tsegismont** [comment]
@vietj good point, I only thought about RxJava2, but alt langs implementation like Scala could also benefit.

Nevertheless, the build fails with  a `Handler<Future<@Nullable T>>` parameter. I will create an issue in codegen. Can I go ahead and merge this one in the meantime?

File: src/main/java/io/vertx/core/shareddata/AsyncMap.java (hunk 7 above)
Comment (vietj) [reply src/main/java/io/vertx/core/shareddata/AsyncMap.java]: ah ok makese sense then, perhaps we should say it in the javadoc as well then

**Comment by vietj** [comment]
+1 for issue in codegen, however I think we shall keep this issue open until we fix it in codegen

File: src/main/java/io/vertx/core/shareddata/AsyncMap.java (hunk 6 above)
Comment (vietj) [reply src/main/java/io/vertx/core/shareddata/AsyncMap.java]: ah ok makese sense then, perhaps we should say it in the javadoc as well then

**Comment by tsegismont** [comment]
@vietj all the changes are in

**Comment by tsegismont** [comment]
@vietj I just rebased and fixed this one after closing vert-x3/vertx-codegen#180

Can you please take another look (just a couple of classes and a few lines changes)? Thanks

**Comment by vietj** [comment]
ideally we should declare

```
<@Nullable T> void executeBlocking(Future<T> fut, Handler<AsyncResult<T>> handler)
```

but codegen does not support this declaration (yet)

so for now it's fine the accept the PR as is.
