### PR TITLE
Fixes #1573 Blocked thread warning when opening or closing an AsyncFile

### LINKED ISSUE #1573: Blocked thread warning when opening or closing an AsyncFile
Users have reported blocked thread warning when opening or closing an AsyncFile.

Here are example stack traces:

```
io.vertx.core.VertxException: Thread blocked
        at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
        at java.io.File.exists(File.java:819)
        at io.vertx.core.impl.FileResolver.resolveFile(FileResolver.java:103)
        at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:657)
        at io.vertx.core.file.impl.FileSystemImpl$14.<init>(FileSystemImpl.java:736)
        at io.vertx.core.file.impl.FileSystemImpl.openInternal(FileSystemImpl.java:735)
        at io.vertx.core.file.impl.FileSystemImpl.open(FileSystemImpl.java:299)
        at io.vertx.core.http.impl.HttpServerFileUploadImpl.streamToFileSystem(HttpServerFileUploadImpl.java:148)
```

and

```
io.vertx.core.VertxException: Thread blocked
	at sun.nio.ch.WindowsAsynchronousFileChannelImpl.close0(Native Method)
	at sun.nio.ch.WindowsAsynchronousFileChannelImpl.close(WindowsAsynchronousFileChannelImpl.java:142)
	at io.vertx.core.file.impl.AsyncFileImpl.doClose(AsyncFileImpl.java:464)
	at io.vertx.core.file.impl.AsyncFileImpl.closeInternal(AsyncFileImpl.java:480)
	at io.vertx.core.file.impl.AsyncFileImpl.close(AsyncFileImpl.java:117)
	at io.vertx.rxjava.core.file.AsyncFile.close(AsyncFile.java:143)
```

One user provided more details and reported he was using a mapped Windows shared drive.

I have been able to reproduce the opening issue by a slow network filesystem (with twickle and nbd).

### PR DESCRIPTION
**Pull request by tsegismont**
Resolving a file is a blocking operation. When creating path as a field, the value is computed when the anonymous class is created (wrong thread), not when the blocking action is executed.

AsyncFileChannel#close operation is also blocking and must executed on a worker thread.

### CODE REVIEW

File: src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java [hunk 1]
```diff
@@ -459,16 +459,19 @@ private void checkContext() {
...
-      ch.close();
-      res.complete(null);
-    } catch (IOException e) {
-      res.fail(e);
-    }
-    if (handler != null) {
-      vertx.runOnContext(v -> handler.handle(res));
-    }
+    ContextImpl handlerContext = vertx.getOrCreateContext();
+    context.executeBlocking((Future<Void> res) -> {
```
Comment (vietj) [inline src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java]: execute on `handlerContext` directly and pass the `handler` as `resultHandler` of `executeBlocking`

Comment (tsegismont) [inline src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java]: Done

2016-08-18 14:44 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by shravanAngadi** [comment]
What happens in case of async read/write operations? I can still see them getting blocked.

**Comment by tsegismont** [comment]
If you get thread blocked warning for async read/write, please create a
separate issue with a reproducer. Thanks

2016-08-31 10:03 GMT+02:00 shravanAngadi <notifications@github.com>:

**Comment by shravanAngadi** [comment]
The code works fine most of the time. A reproducers would be just a simple file read/write program which performs the operations on a very slow drive, say like a slow network drive.

**Comment by tsegismont** [comment]
Ok then please create the separate issue with this and most importantly,
the stack trace accompanying the blocked thread warning

2016-08-31 10:58 GMT+02:00 shravanAngadi <notifications@github.com>:
